# -*- coding: utf-8 -*-
"""[0] HelloWorld.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xT884F22R1wWyLE-3sBtoEkDkXr3uOwx
"""

print("Hello, World")

"""Variables & Data Types"""

name = "Alice"      # String
age = 25            # Integer
height = 5.9        # Float
is_student = True   # Boolean

"""Basic Operations"""

a = 10 + 5    # Addition
b = 10 * 2    # Multiplication
c = 10 / 3    # Division

"""Conditional Statements (if, elif, else):

"""

num = 7
if num > 0:
    print("Positive")
else:
    print("Negative")

"""Loops (for, while):

"""

# For loop
for i in range(5):
    print(i)

# While loop
count = 0
while count < 3:
    print("Looping!")
    count += 1

"""Functions"""

def greet(name):
    return f"Hello, {name}!"
print(greet("UIU"))

#Lists
fruits = ["apple", "banana", "cherry"]
fruits.append("orange")
print(fruits[3])

#Dictionaries
person = {"name": "Alice", "age": 25, "city": "New York"}
print(person["name"])

"""Working with Data (Pandas)"""

#DataFrames (Excel-like tables)

import pandas as pd
data = {"Name": ["Alice", "Bob"], "Age": [25, 30]}
df = pd.DataFrame(data)
print(df)

#Basic Data Analysis
#df.head()
df.describe()

"""Visualization (Matplotlib/Seaborn)

"""

import matplotlib.pyplot as plt
x = [1, 2, 3]
y = [2, 4, 1]
plt.plot(x, y)
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.show()